FROM nginx:stable-alpine

COPY default.conf /etc/nginx
COPY default.conf /etc/nginx/conf.d
# sudo amazon-linux-extras install nginx1
# sudo vi /etc/nginx/nginx.conf
# sudo /etc/init.d/nginx start

EXPOSE 80